### ISSUE TITLE
error: ‘runtime_error’ is not a member of ‘std’

### ISSUE THREAD

**Issue by davidjsherman** [enki-community/enki#43]
Introduced in 673f995a4dac5132970296da968172a31265f359, [enki/Geometry.cpp#L158](https://github.com/enki-community/enki/blame/master/enki/Geometry.cpp#L158).

**Comment by davidjsherman** [comment]
Resolved by #44
